name: 🚀 Build & Run

on: 
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: ✨ Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'adopt'
      - name: 🏗️ Build with Maven
        run: mvn -B package --file pom.xml
      - name: 🌐 Install Google Chrome 
        run: |
          chmod +x ./InstallChrome.sh
          ./InstallChrome.sh
      - name: 🏃 Run jar file 
        run: java -jar target/WorldathleticsKeyUpdater-1.0-SNAPSHOT-shaded.jar
      - uses: actions/setup-node@v4
        with: 
          node-version: 22
          check-latest: true 
      - name: 🚀 Push to Stellate
        run: npx stellate push 
        env: 
          STELLATE_TOKEN: ${{ secrets.STELLATE_TOKEN }}